collections:
  projects:
    output: true
    permalink: /projects/projects.md
  experience:
    output: true
    permalink: /experience/positions.md
  education:
    output: true
    permalink: /education/degrees.md

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: category
  - scope:
      path: ""
      type: experience
    values:
      layout: category
  - scope:
      path: ""
      type: education
    values:
      layout: category
